Hous 63
HouseRent16/PGPI-G2.11 pull request #62
Opened 2023-11-30 16:17 UTC by sergiosant02

Se automatiza el envio de correos cuando se realiza la reserva

2023-12-02 10:12 UTC, sergiosant02 commented
Se ha cambiado el estilo y el texto para que cumpla los requisitos.
<img width="782" alt="Captura de pantalla 2023-12-02 a las 11 12 33" src="https://github.com/HouseRent16/PGPI-G2.11/assets/54277294/904eb32b-d014-40e6-a38f-e4f376b75d58">

2023-12-02 18:01 UTC, marvicmar requested changes

2023-12-02 18:01 UTC, marvicmar commented on src/houseRent/db.sqlite3
Elimina este archivo, ya que da conflictos con la que se encuentra en develop.

2023-12-03 11:45 UTC, JuanCarlosRL commented on src/houseRent/db.sqlite3
Ya está arreglado

2023-12-03 12:02 UTC, marvicmar approved these changes
Todo parece correcto

2023-12-03 12:02 UTC, merged